# Generated by Django 4.0.2 on 2022-04-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_name', models.CharField(max_length=50)),
                ('sneaker_model', models.CharField(max_length=50)),
                ('sneaker_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sneaker_size', models.IntegerField()),
            ],
        ),
    ]
