# Generated by Django 4.0.2 on 2022-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sneaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='sneaker_sex',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
