# Generated by Django 4.0.2 on 2022-04-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sneaker_sneaker_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='sneaker_sex',
            new_name='sneaker_for',
        ),
    ]
