# Generated by Django 4.0.2 on 2022-04-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_sneaker_sex_sneaker_sneaker_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='sneaker_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='sneaker_price',
            field=models.IntegerField(null=True),
        ),
    ]
