# Generated by Django 4.0.2 on 2022-05-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experiencecategory_jobcategory_jobvacancies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancies',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.jobcategory'),
        ),
        migrations.AddField(
            model_name='jobvacancies',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.experiencecategory'),
        ),
    ]
