# Generated by Django 4.0.2 on 2022-05-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_jobvacancies_cat_jobvacancies_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancies',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/vacancy'),
        ),
    ]
