# Generated by Django 4.0.2 on 2022-04-21 10:19

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sneaker_sneaker_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='sneaker_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
