# Generated by Django 4.0.2 on 2022-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_jobvacancies_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancies',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
