# Generated by Django 4.0.2 on 2022-04-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sneaker_sneaker_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SneakerForKid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_name', models.CharField(max_length=50)),
                ('sneaker_model', models.CharField(max_length=50)),
                ('sneaker_image', models.ImageField(blank=True, null=True, upload_to='imageskid/')),
                ('sneaker_size', models.CharField(blank=True, choices=[('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34')], max_length=2, null=True)),
                ('sneaker_price', models.IntegerField(null=True)),
                ('sneaker_category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SneakerForMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_name', models.CharField(max_length=50)),
                ('sneaker_model', models.CharField(max_length=50)),
                ('sneaker_image', models.ImageField(blank=True, null=True, upload_to='imagesman/')),
                ('sneaker_size', models.CharField(blank=True, choices=[('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=2, null=True)),
                ('sneaker_price', models.IntegerField(null=True)),
                ('sneaker_category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SneakerForWoman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_name', models.CharField(max_length=50)),
                ('sneaker_model', models.CharField(max_length=50)),
                ('sneaker_image', models.ImageField(blank=True, null=True, upload_to='imageswoman/')),
                ('sneaker_size', models.CharField(blank=True, choices=[('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39')], max_length=2, null=True)),
                ('sneaker_price', models.IntegerField(null=True)),
                ('sneaker_category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='sneaker_size',
            field=models.IntegerField(),
        ),
    ]
