# Generated by Django 4.0.2 on 2022-04-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sneakerforkid_sneakerforman_sneakerforwoman_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_category', models.CharField(blank=True, choices=[('Run', 'Run'), ('Volleyball', 'Volleyball'), ('Outerwear', 'Outerwear'), ('Collaborations', 'Collaborations')], max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sneaker',
        ),
    ]
