# Generated by Django 4.0.2 on 2022-04-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_user_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
